# Pull official base image 
FROM python:3.10-slim

# Set working directory
WORKDIR /usr/src/app/

# Set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get install -y gcc python3-dev musl-dev libmagic1 libffi-dev netcat-traditional \
    build-essential libpq-dev

# RUN curl -sSL https://install.python-poetry.org | python3 - 
# install python dependencies
# COPY ./pyproject.toml .
# COPY ./poetry.lock .
# RUN /root/.local/bin/poetry install
# EXPOSE 8000
# RUN export PATH="$HOME/.local/bin:$PATH"
# RUN source ~/.bashrc
COPY poetry.lock pyproject.toml /usr/src/app/

RUN pip3 install poetry
#RUN poetry config virtualenvs.create false
# Install dependencies
RUN poetry install

# Copy entrypoint.sh
COPY ./docker/dev/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

COPY . /usr/src/app/

ENTRYPOINT [ "/entrypoint.sh" ]